app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from widgets.common.task_info import task_info

def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path('admin/', admin.site.urls),
    path('author_code/', include('author_code.urls')),
    path('<task_id>/', task_info, name='task_status')
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/author_code/urls.py
from django.urls import path
from .views import index
from .views import Author
from .views import AuthorSymbol
from .views import Work
from .views import upload_AuthorSymbol
from .views import upload_CutterSanbornThreeFigureAuthorTable
from .views import upload_LanguageCode
from .views import upload_Author
from .views import upload_SubjectCode
from .views import ajax
from .views import maintenance_author_symbol
from .views import maintenance_work_number

app_name = 'author_code'
urlpatterns = [
    path('', index.index.as_view(), name='index'),
    path('Author/<uuid:pk>/', Author.AuthorRequest.as_view(), name='Author'),
    path('Author/detail/<uuid:pk>/', Author.AuthorDetail.as_view(), name='AuthorDetail'),
    path('Author/create/', Author.AuthorCreate.as_view(), name='AuthorCreate'),
    path('AuthorSymbol/detail/<uuid:pk>/', AuthorSymbol.AuthorSymbolDetail.as_view(), name='AuthorSymbolDetail'),
    path('AuthorSymbol/create/', AuthorSymbol.AuthorSymbolCreate.as_view(), name='AuthorSymbolCreate'),
    path('AuthorSymbol/delete/<uuid:pk>/', AuthorSymbol.AuthorSymbolDelete.as_view(), name='AuthorSymbolDelete'),
    path('Work/edit/<uuid:pk>/', Work.WorkEdit.as_view(), name='WorkEdit'),
    path('Work/create/', Work.WorkCreate.as_view(), name='WorkCreate'),
    path('Work/delete/<uuid:pk>/', Work.WorkDelete.as_view(), name='WorkDelete'),
    path(
        'upload/CutterSanbornThreeFigureAuthorTable/',
        upload_CutterSanbornThreeFigureAuthorTable.upload, name='Upload'
    ),
    path('upload/LanguageCode/', upload_LanguageCode.upload, name='UploadLanguageCode'),
    path('upload/Author/', upload_Author.upload, name='UploadAuthor'),
    path('upload/AuthorSymbol', upload_AuthorSymbol.Upload.as_view(), name='UploadAuthorSymbol'),
    path('upload/SubjectCode/', upload_SubjectCode.upload, name='UploadSubjectCode'),
    path('ajax/authorsymbol/search/', ajax.ajax_authorsymbol_search, name='ajax_authorsymbol_search'),
    path('ajax/usedsymbol/search/', ajax.ajax_usedsymbol_search, name='ajax_usedsymbol_search'),
    path('ajax/maintenance/AuthorSymbol', ajax.ajax_maintenance_author_symbol, name='ajax_maintenance_author_symbol'),
    path('ajax/maintenance/WorkNumber', ajax.ajax_maintenance_work_number, name='ajax_maintenance_work_number'),
    path('ajax/bulk/create/works', ajax.ajax_bulk_create_works, name='ajax_bulk_create_works'),
    path('maintenance/author/', maintenance_author_symbol.AuthorSymbolMaintenance.as_view(), name='maintenance_author'),
    path('maintenance/work/', maintenance_work_number.WorkNumberMaintenance.as_view(), name='maintenance_work'),
]

app/author_code/views/Author.py
from urllib.parse import urlencode
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import View, DetailView, CreateView
from author_code.models import CutterSanbornThreeFigureAuthorTable, Author, AuthorSymbol
from author_code.forms import AuthorForm


class AuthorRequest(View):
    def get(self, request, *args, **kwargs):
        """GETリクエスト"""
        try:
            author = Author.objects.get(AuthorId=kwargs["pk"])

            if author.Heading == "(新規作成)":
                url = reverse('author_code:AuthorCreate')
                param = urlencode({
                    'symbol': author.AuthorSymbol_id,
                })
                url = f'{url}?{param}'
                return redirect(url)

            else:
                return redirect('author_code:AuthorDetail', pk=author.AuthorId)

        except Author.DoesNotExist:
            raise Http404("No Author matches the given query")


class AuthorDetail(DetailView):
    template_name = "author_code/detail_Author.html"
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]

        try:
            symbol_list = AuthorSymbol.objects.filter(AuthorId=pk).order_by('LanguageCode')
            context["symbol_list"] = symbol_list
        except AuthorSymbol.DoesNotExist:
            pass

        return context


class AuthorCreate(CreateView):
    template_name = "author_code/create_Author.html"
    model = Author
    form_class = AuthorForm

    def get_initial(self):
        initial = super().get_initial()
        symbol = CutterSanbornThreeFigureAuthorTable.objects.get(AuthorSymbol=self.request.GET['symbol'])
        initial['AuthorSymbol'] = symbol
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        symbol = self.request.GET['symbol']
        context['author'] = {
            'AuthorSymbol_id': symbol,
            'Heading': '(新規作成)',
        }
        return context

    def get_success_url(self):
        return reverse('author_code:AuthorDetail', kwargs={'pk': self.object.AuthorId})

app/author_code/views/AuthorSymbol.py
from urllib.parse import urlencode
from django.urls import reverse
from django.views.generic import DetailView, CreateView, DeleteView
from author_code.models import Author, AuthorSymbol, Work
from author_code.forms import AuthorSymbolForm
import uuid


class AuthorSymbolDetail(DetailView):
    template_name = "author_code/detail_AuthorSymbol.html"
    model = AuthorSymbol

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]

        try:
            work_list = Work.objects.filter(AuthorSymbolId=pk).order_by("WN", "SN")
            context["work_list"] = work_list
        except Work.DoesNotExist:
            pass

        return context


class AuthorSymbolCreate(CreateView):
    template_name = "author_code/create_AuthorSymbol.html"
    model = AuthorSymbol
    form_class = AuthorSymbolForm

    def get_initial(self):
        initial = super().get_initial()
        author = Author.objects.get(AuthorId=self.request.GET['author'])
        initial = {
            'AuthorId': author,
            'SubjectCode': "9□-8",
            'AuthorSymbol': author.AuthorSymbol
        }
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = Author.objects.get(AuthorId=uuid.UUID(self.request.GET['author']))
        context['author'] = author
        return context

    def get_success_url(self):
        url = "".join([reverse('author_code:WorkCreate'), '?', urlencode(dict(symbol=self.object.AuthorSymbolId))])
        return url


class AuthorSymbolDelete(DeleteView):
    template_name = "author_code/delete_AuthorSymbol.html"
    model = AuthorSymbol

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        other_symbol = AuthorSymbol.objects.filter(AuthorId=self.object.AuthorId_id).count()
        if other_symbol == 0:
            author = Author.objects.get(AuthorId=self.object.AuthorId_id)
            author.delete()
        return result

    def get_success_url(self):
        url = reverse('author_code:index')
        return url

app/author_code/views/Work.py
from django.urls import reverse
from django.views.generic import UpdateView, CreateView, DeleteView
from author_code.models import AuthorSymbol, Work
from author_code.forms import WorkForm
from widgets.author_code.calc_series_no import calc_series_no, calc_work_no
import uuid


class WorkEdit(UpdateView):
    template_name = "author_code/edit_Work.html"
    model = Work
    form_class = WorkForm

    def form_valid(self, form):
        form.instance.WN = calc_work_no(form.cleaned_data["WorkNumber"])

        if form.cleaned_data["SeriesNumber"]:
            series = calc_series_no(form.cleaned_data["SeriesNumber"])
            form.instance.SN = series

        return super(WorkEdit, self).form_valid(form)

    def get_success_url(self):
        return reverse('author_code:AuthorSymbolDetail', kwargs={'pk': self.object.AuthorSymbolId_id})


class WorkCreate(CreateView):
    template_name = "author_code/create_Work.html"
    model = Work
    form_class = WorkForm

    def get_initial(self):
        initial = super().get_initial()
        symbol = AuthorSymbol.objects.get(AuthorSymbolId=uuid.UUID(self.request.GET['symbol']))
        initial['AuthorSymbolId'] = symbol
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        symbol = AuthorSymbol.objects.get(AuthorSymbolId=uuid.UUID(self.request.GET['symbol']))
        context['symbol'] = symbol
        return context

    def form_valid(self, form):
        form.instance.WN = calc_work_no(form.cleaned_data["WorkNumber"])

        if form.cleaned_data["SeriesNumber"]:
            series = calc_series_no(form.cleaned_data["SeriesNumber"])
            form.instance.SN = series

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('author_code:AuthorSymbolDetail', kwargs={'pk': self.object.AuthorSymbolId_id})


class WorkDelete(DeleteView):
    template_name = "author_code/delete_Work.html"
    model = Work

    def get_success_url(self):
        return reverse('author_code:AuthorSymbolDetail', kwargs={'pk': self.object.AuthorSymbolId_id})

app/author_code/views/ajax.py
from author_code.models import Author, AuthorSymbol, Work
from author_code.tasks import merge, recalculation, bulk_create_works
from widgets.author_code import author_table_query, bulk_create
from django.http import JsonResponse
from django.urls import reverse
from django.db.models import Q
import pandas as pd
import io


def ajax_authorsymbol_search(request):
    keyword = request.GET.get('keyword')
    symbol_list = []
    print(keyword)
    if keyword:
        result = author_table_query.query(keyword)
        items = Author.objects.filter(
            Q(AuthorSymbol=result) |
            Q(Heading__startswith=keyword)
        ).distinct("Heading").order_by("Heading")

        for item in items:
            title = str(item.AuthorSymbol_id) + " | " + str(item.Heading)
            if '新規作成' in str(item.Heading):
                title += " " + str(result.AuthorName)
            preview = {
                "title": title,
                "url": reverse('author_code:Author', kwargs={'pk': item.pk}),
            }
            symbol_list.append(preview)

    data = {
        'symbol_list': symbol_list,
    }

    return JsonResponse(data)


def ajax_usedsymbol_search(request):
    keyword = {
        "LanguageCode": request.GET.get("LanguageCode"),
        "SubjectCode": request.GET.get("SubjectCode"),
        "AuthorSymbol": request.GET.get("AuthorSymbol"),
    }
    symbol_list = []

    if keyword:
        results = AuthorSymbol.objects.filter(
            LanguageCode=keyword["LanguageCode"],
            SubjectCode=keyword["SubjectCode"],
            AuthorSymbol__icontains=keyword["AuthorSymbol"],
        ).order_by("AuthorSymbol")

        if len(results) != 0:
            for result in results:
                preview = str(result.AuthorSymbol) + " | " + result.AuthorId.Heading
                symbol_list.append(preview)

        else:
            symbol_list.append("指定の言語記号、分類記号で使用されている著者記号はありません")

    data = {
        'symbol_list': symbol_list,
    }

    return JsonResponse(data)


def ajax_maintenance_author_symbol(request):
    id = request.POST.get('id')
    if id:
        task = merge.delay(id)
        data = {
            'task_id': task.id
        }
        return JsonResponse(data)
    return None


def ajax_maintenance_work_number(request):
    task = recalculation.delay()
    max_count = Work.objects.all().count()
    data = {
        'task_id': task.id,
        'max_count': max_count
    }
    return JsonResponse(data)


def ajax_bulk_create_works(request):
    extension = request.FILES['data'].name.split(".")[1].lower()
    if extension == ".csv":
        df = pd.read_csv(request.FILES['data'], header=None, dtype=str, na_filter=False)
    else:
        df = pd.read_table(request.FILES['data'], header=None, dtype=str, na_filter=False)

    if not df.empty:
        task = bulk_create_works.delay(df.to_json())
        data = {
            'task_id': task.id,
        }
        return JsonResponse(data)
    return None

app/author_code/views/index.py
from django.views.generic import TemplateView


class index(TemplateView):
    template_name = 'author_code/index.html'

app/author_code/views/maintenance_author_symbol.py
from django.views.generic import TemplateView
from django_pandas.io import read_frame
from django import forms
from author_code.models import AuthorSymbol


class AuthorSymbolMaintenance(TemplateView):
    template_name = 'author_code/maintenance_author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # AuthorSymbol の抽出
        df = read_frame(AuthorSymbol.objects.all(), fieldnames=[
            'AuthorSymbolId',
            'AuthorId__Heading',
            'LanguageCode__LanguageCode',
            'SubjectCode__SubjectCode',
            'AuthorSymbol',
        ]).rename(columns={
            'AuthorId__Heading': 'Heading',
            'LanguageCode__LanguageCode': 'LanguageCode',
            'SubjectCode__SubjectCode': 'SubjectCode',
        })
        # 重複の削除
        df = df[df.duplicated(
            keep=False,
            subset=[
                'LanguageCode',
                'SubjectCode',
                'AuthorSymbol',
            ]
        )]
        # LanguageCode, SubjectCode, AuthorSymbol でマルチインデックス化
        df = df.sort_values(['LanguageCode', 'SubjectCode', 'AuthorSymbol'])
        df = df.set_index(['LanguageCode', 'SubjectCode', 'AuthorSymbol'])

        # form の作成
        form_list = []
        for index, data in df.groupby(level=['LanguageCode', 'SubjectCode', 'AuthorSymbol']):
            get_tuple = lambda x: (x['AuthorSymbolId'], x['Heading'])
            data['choice'] = data.apply(get_tuple, axis=1)
            choices = data['choice'].to_list()
            form = MaintenanceForm()
            form.fields['select'].label = '/'.join(str(x) for x in index)
            form.fields['select'].choices = choices
            form_list.append(form)

        context['form_list'] = form_list
        return context

class MaintenanceForm(forms.Form):
    select = forms.ChoiceField(widget=forms.RadioSelect)

app/author_code/views/maintenance_work_number.py
from django.views.generic import TemplateView


class WorkNumberMaintenance(TemplateView):
    template_name = 'author_code/maintenance_work_number.html'

app/author_code/views/upload_Author.py
import csv
from io import TextIOWrapper

from author_code.models import Author
from author_code.models import CutterSanbornThreeFigureAuthorTable
from django.shortcuts import render


# Create your views here.

def upload(request):
    if 'csv' in request.FILES:
        form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
        csv_file = csv.reader(form_data)
        bulk = []
        for line in csv_file:
            AuthorSymbol = CutterSanbornThreeFigureAuthorTable.objects.get(AuthorSymbol=line[0])
            author = Author(Heading=line[1], AuthorSymbol=AuthorSymbol)
            bulk.append(author)

        Author.objects.bulk_create(bulk)

        return render(request, 'author_code/upload_Author.html')

    else:
        return render(request, 'author_code/upload_Author.html')

app/author_code/views/upload_AuthorSymbol.py
from django.views.generic import TemplateView


# Create your views here.


class Upload(TemplateView):
    template_name = 'author_code/upload_AuthorSymbol.html'

app/author_code/views/upload_CutterSanbornThreeFigureAuthorTable.py
import csv
from io import TextIOWrapper

from author_code.models import CutterSanbornThreeFigureAuthorTable
from django.shortcuts import render


# Create your views here.

def upload(request):
    if 'csv' in request.FILES:
        form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
        csv_file = csv.reader(form_data)
        bulk = []
        for line in csv_file:
            authorsymbol = CutterSanbornThreeFigureAuthorTable(AuthorSymbol=line[0], AuthorName=line[1])
            bulk.append(authorsymbol)

        CutterSanbornThreeFigureAuthorTable.objects.bulk_create(bulk)

        return render(request, 'author_code/upload_CutterSanbornThreeFigureAuthorTable.html')

    else:
        return render(request, 'author_code/upload_CutterSanbornThreeFigureAuthorTable.html')

app/author_code/views/upload_LanguageCode.py
import csv
from io import TextIOWrapper

from author_code.models import LanguageCode
from django.shortcuts import render


# Create your views here.

def upload(request):
    if 'csv' in request.FILES:
        form_data = TextIOWrapper(request.FILES['csv'].file, encoding='utf-8')
        csv_file = csv.reader(form_data)
        bulk = []
        for line in csv_file:
            languagecode = LanguageCode(LanguageCode=line[0], Language=line[1])
            bulk.append(languagecode)

        LanguageCode.objects.bulk_create(bulk)

        return render(request, 'author_code/upload_LanguageCode.html')

    else:
        return render(request, 'author_code/upload_LanguageCode.html')

app/templates/author_code/base.html
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- My Style CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'author_code/css/author_code.css' %}">

    {% block head %}{% endblock %}

</head>
<body>
    <div id ='wrapper'>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top mb-5">
            <a class="navbar-brand" href="{% url 'author_code:index' %}">著者記号管理システム</a>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            一括登録
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'author_code:Upload' %}">Cutter Sanborn Author Table</a>
                            <a class="dropdown-item" href="{% url 'author_code:UploadLanguageCode' %}">言語記号一括登録</a>
                            <a class="dropdown-item" href="{% url 'author_code:UploadAuthor' %}">著者一括登録</a>
                            <a class="dropdown-item" href="{% url 'author_code:UploadSubjectCode' %}">主題 (請求記号２段目)一括登録</a>
                            <a class="dropdown-item" href="{% url 'author_code:UploadAuthorSymbol' %}">作品等データ一括登録</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            データメンテナンス
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'author_code:maintenance_author' %}">著者記号重複マージ</a>
                            <a class="dropdown-item" href="{% url 'author_code:maintenance_work' %}">作品番号並び順再設定</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        {% block header %}{% endblock %}

        <main class="mb-5">
            <div class="container">
                {% block contents %}{% endblock %}
            </div>
        </main>
        <footer class="footer bg-dark fixed-bottom">
            <div class="container">
            <p class="text-muted">Copyright &copy; TUFS Library Cataloging Section 2020</p>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        {% block scripts %}{% endblock %}
    </div>
</body>
</html>

app/templates/author_code/detail_Author.html
{% extends 'author_code/base.html' %}
{% load static %}

{% block title %}著者記号一覧{% endblock %}

{% block contents %}

<h3 class="headline">{{ author.AuthorSymbol_id }} | {{ author.Heading }}</h3>

<table class="table table-striped">

    <tr>
        <th class="align-middle text-center">言語記号</th>
        <th class="align-middle text-center">分類記号</th>
        <th class="align-middle text-center">著者記号</th>
        <th class="align-middle text-center"></th>
        <th class="align-middle text-center"></th>
    </tr>
    {% if symbol_list %}
    {% for symbol in symbol_list %}
    <tr>
        <td class="align-middle text-center text-center">{{ symbol.LanguageCode_id }}</td>
        <td class="align-middle text-center">{{ symbol.SubjectCode_id }}</td>
        <td class="align-middle text-center">{{ symbol.AuthorSymbol }}</td>
        <td class="align-middle text-center"><a href="{% url 'author_code:AuthorSymbolDetail' symbol.pk %}" target="_self"><button type="button" class="btn btn-outline-info">追加</button></a></td>
        <td class="align-middle text-center"><a href="{% url 'author_code:AuthorSymbolDelete' symbol.pk %}" target="_self"><button type="button" class="btn btn-outline-danger">削除</button></a></td>
    </tr>
    {% endfor %}
    {% endif %}
    <tr>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"><a href="{% url 'author_code:AuthorSymbolCreate' %}?author={{ author.pk }}" target="_self"><button type="button" class="btn btn-outline-danger">新規</button></a></td>
        <td class="align-middle text-center"></td>
    </tr>

</table>

{% endblock %}

app/templates/author_code/detail_AuthorSymbol.html
{% extends 'author_code/base.html' %}
{% load static %}

{% block title %}作品一覧{% endblock %}

{% block contents %}

<h3 class="headline">{{ authorsymbol.AuthorId.AuthorSymbol_id }} | {{ authorsymbol.AuthorId.Heading }}</h3>
<h4>{{ authorsymbol.LanguageCode_id }}/{{ authorsymbol.SubjectCode_id }}/{{ authorsymbol.AuthorSymbol }}</h4>

<table class="table table-striped">

    <tr>
        <th class="align-middle text-center">作品番号</th>
        <th class="align-middle text-center">シリーズ番号</th>
        <th class="align-middle text-center">書名</th>
        <th class="align-middle text-center">図書ID</th>
        <th class="align-middle text-center"></th>
        <th class="align-middle text-center"></th>
    </tr>
    {% if work_list %}
    {% for work in work_list %}
    <tr>
        <td class="align-middle text-center">{{ work.WorkNumber }}</td>
        {% if work.SeriesNumber is None %}
            <td class="align-middle text-center"></td>
        {% else %}
            <td class="align-middle text-center">{{ work.SeriesNumber }}</td>
        {% endif %}
        <td class="align-middle text-center">{{ work.BookTitle }}</td>
        <td class="align-middle text-center">{{ work.BookId }}</td>
        <td class="align-middle text-center"><a href="{% url 'author_code:WorkEdit' work.pk %}" target="_self"><button type="button" class="btn btn-outline-info">編集</button></a></td>
        <td class="align-middle text-center"><a href="{% url 'author_code:WorkDelete' work.pk %}" target="_self"><button type="button" class="btn btn-outline-danger">削除</button></a></td>
    </tr>
    {% endfor %}
    {% endif %}
    <tr>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"></td>
        <td class="align-middle text-center"><a href="{% url 'author_code:WorkCreate' %}?symbol={{ authorsymbol.pk }}" target="_self"><button type="button" class="btn btn-outline-danger">新規</button></a></td>
    </tr>

</table>
<div class="text-right">
    <a href="{% url 'author_code:AuthorDetail' authorsymbol.AuthorId_id %}" target="_self"><button type="button" class="btn btn-secondary">戻る</button></a>
</div>
{% endblock %}

app/templates/author_code/index.html
{% extends 'author_code/base.html' %}
{% load static %}

{% block title %}TOP{% endblock %}

{% block contents %}

<h3 class="headline">著者記号検索システム</h3>

<div class="form-group">
    <form>
        <input class="form-control" type="text" id="search-text" placeholder="著者名をアルファベットで入力してください">
    </form>
</div>

<div id="result">

</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).on('keyup', '#search-text', function(e) {
        console.log($('#search-text').val())
        $.ajax({
            'url': '{% url "author_code:ajax_authorsymbol_search" %}',
            'type': 'GET',
            'data': {
                'keyword': $('#search-text').val(),
            },
            'dataType': 'json'
        }).done( response => {
            $('#result').empty();

            for (const symbol of response.symbol_list) {
                console.log(symbol)
                const base = '{{ HTTP_HOST }}';
                const a = '<a href="' + base + symbol.url + '"target="_self">';
                const p = '<p>' + a + symbol.title + '</a></p>'

                $('#result').append(p);
            }
        });
    });
</script>
{% endblock %}

app/templates/author_code/upload_Author.html
{% extends 'author_code/base.html' %}
{% load static %}
{% block title %}Author を一括アップロードする{% endblock %}

{% block head %}
<link rel='stylesheet' href='https://cdn.rawgit.com/JeremyFagis/dropify/master/dist/css/dropify.css' />
{% endblock %}

{% block contents %}

<h3 class="headline">CSV ファイルをアップロード</h3>
<form action="{% url 'author_code:UploadAuthor' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">アップロード</button>
</form>

{% endblock %}

{% block scripts %}
<script src='https://cdn.rawgit.com/JeremyFagis/dropify/master/dist/js/dropify.js'></script>
<script>
$(function(){
  $('.dropify').dropify();
})
</script>
{% endblock %}